PlanB-Network/bitcoin-educational-content

courses/secu101/fr.md

First fix of secu 101 urgent to add

Fix secu101

---

courses/secu101/fr.md

fix error on the # and ## for chapter 2

Fix typos secu101

---

courses/secu101/de.md
courses/secu101/en.md
courses/secu101/es.md
courses/secu101/fr.md
courses/secu101/it.md
courses/secu101/pt.md

Review of the SECU 101 courses, add a couple of section and made it more course like. I've retranslated in every language to fix the short term Interntional version. 
We are still missing 3 important thing: 
- Renaud review of thr FR version 
- include images
- create the tutorials
THe tutorials shall be created on the tutorial section so we just link them via a componant. For now tho, let's merge this to have a clean secu 101 courses as V0.8

Fix secu101 and traduction

---

courses/min201/fr.md

Fix min201 typos

---

courses/btc102/de.md
courses/btc102/en.md
courses/btc102/es.md
courses/btc102/fr.md
courses/btc102/it.md
courses/btc102/pt.md

fix title btc 102

---

courses/ln201/de.md
courses/ln201/en.md
courses/ln201/es.md
courses/ln201/fr.md
courses/ln201/it.md
courses/ln201/pt.md

Fix ln201 curriculum structure

---

courses/btc102/fr.md

Fix btc 102 fr

---

courses/crypto302/en.md

hot fix crypto302

---

courses/crypto302/en.md

Hot fix crypto302 2

---

courses/crypto302/en.md

Fix doublon des cours. 
I didn't change the chapter number as it's his book and it make no sense to change it at this stage of the process. it wll just make it harder for him to review

Fix doublon Crypto302

---

tutorials/node/ronin-dojo/de.md
tutorials/node/ronin-dojo/en.md
tutorials/node/ronin-dojo/es.md
tutorials/node/ronin-dojo/it.md
tutorials/node/ronin-dojo/pt.md

add bash translation ronin dojo pt it en de es

---

tutorials/privacy/paynym-bip47/de.md
tutorials/privacy/paynym-bip47/en.md
tutorials/privacy/paynym-bip47/es.md
tutorials/privacy/paynym-bip47/fr.md
tutorials/privacy/paynym-bip47/it.md
tutorials/privacy/paynym-bip47/pt.md
tutorials/privacy/paynym-bip47/tutorial.yml

add BIP 47 multi language

---

courses/btc101/it.md

Typos and minor adjustments

---

courses/btc102/fr.md

fix typos btc102

---

courses/econ204/fr.md

fix url on btc204

---

tutorials/wallet/sparrow/es.md

Update translation tutorials Sparrow es.md Spanish version

Update translation tutorials Sparrow es.md

---

README.md

je t'envoie la balle est un audio

add v0.5 of join network

---

courses/secu101/de.md
courses/secu101/en.md
courses/secu101/es.md
courses/secu101/fr.md
courses/secu101/it.md
courses/secu101/pt.md

Fix secu101 description

---

tutorials/mining/attakai/fr.md

Attakai: Grammatical and spelling check up to line 200

Update fr.md until line 200

---

tutorials/mining/attakai/fr.md

Attakai: Grammar and spelling check from line 200 to end of article

Update fr.md from line 200 to end

---

professors/armand_the_parmant/professor.yml

Fix tips professors

---

tutorials/node/watch-tower/de.md
tutorials/node/watch-tower/en.md
tutorials/node/watch-tower/es.md
tutorials/node/watch-tower/fr.md
tutorials/node/watch-tower/it.md
tutorials/node/watch-tower/pt.md

fix credit  and image /

---

tutorials/wallet/blue-wallet/de.md
tutorials/wallet/blue-wallet/en.md
tutorials/wallet/blue-wallet/es.md
tutorials/wallet/blue-wallet/fr.md
tutorials/wallet/blue-wallet/it.md
tutorials/wallet/blue-wallet/pt.md

fix image1

---

tutorials/privacy/tails/de.md
tutorials/privacy/tails/en.md
tutorials/privacy/tails/es.md
tutorials/privacy/tails/fr.md
tutorials/privacy/tails/it.md
tutorials/privacy/tails/pt.md

fix credit

---

courses/btc101/it.md

Fix objectives IT btc101

---

courses/btc101/sw.md
courses/btc102/sw.md
courses/btc205/sw.md
courses/crypto301/sw.md
courses/econ201/sw.md
courses/econ204/sw.md
courses/ln201/sw.md
courses/min201/sw.md
courses/secu101/sw.md

Here is the upload of the first automatic translation in Swahili for these courses:
- btc101
- btc102
- btc205
- ln201
- min201
- secu101
- econ201
- econ204
- crypto301
We now need someone to review these translations before merging into `dev` branch.

upload automatic translation in swahili

---

courses/btc101/af.md
courses/btc102/af.md
courses/btc205/af.md
courses/crypto301/af.md
courses/econ201/af.md
courses/econ204/af.md
courses/ln201/af.md
courses/min201/af.md
courses/secu101/af.md

Here is the upload of the first automatic translation in Afrikaans for these courses:
- btc101
- btc102
- btc205
- ln201
- min201
- secu101
- econ201
- econ204
- crypto301
We now need someone to review these translations before merging into dev branch.

upload automatic translation in afrikaans

---

courses/btc205/de.md
courses/btc205/en.md
courses/btc205/es.md
courses/btc205/it.md
courses/btc205/pt.md

fix erreur EN & remove video bisq

---

courses/crypto302/en.md

fix image crypto 302

---

tutorials/wallet/phoenix/de.md
tutorials/wallet/phoenix/en.md
tutorials/wallet/phoenix/es.md
tutorials/wallet/phoenix/fr.md
tutorials/wallet/phoenix/it.md
tutorials/wallet/phoenix/pt.md

ok to push asi0. fixed for all languages

Fix phoenix wallet issue

---

tutorials/privacy/grapheneos/en.md

ok to merge. Tutorial only in ENG and not in other language/ We can start software if ok

Fix image and video grapen OS ENG

---

courses/tether/course.yml
courses/tether/en.md
professors/seb_bunney/en.yml
professors/seb_bunney/professor.yml

ok to merge. we need to change the course name to stablecoin

add description and fix tether courses

---

courses/btc104/en.md

fix description btc104

---

courses/cuboplus/en.md

add eng description

---

courses/secu101/en.md
courses/secu101/es.md
courses/secu101/fr.md

Add fr section secu101 practice

---

courses/ln201/es.md

add video ESP to ln201

---

tutorials/privacy/payjoin-samourai-wallet/fr.md
tutorials/privacy/payjoin-sparrow-wallet/fr.md
tutorials/privacy/payjoin/fr.md
tutorials/privacy/stonewall-x2/fr.md

Ajout de quelques liens vers des sources externes en fin d'article pour les articles déjà merge (Payjoin, Stowaway SW, Stowaway Sparrow et Stonewall x2).

Ajout liens ressources externes

---

courses/secu101/en.md

fix minor issu secu101 en

---

courses/secu101/de.md
courses/secu101/en.md
courses/secu101/pt.md

various minor change to secu 101

---

professors/jwburgers/de.yml
professors/jwburgers/en.yml
professors/jwburgers/es.yml
professors/jwburgers/fr.yml
professors/jwburgers/it.yml
professors/jwburgers/pt.yml

fix bio markdown

---

professors/southerbitcoiner/professor.yml

fix capital later

---

courses/crypto301/fr.md

add video itw crypto301

---

courses/ln402/en.md

fix image ln 204

---

professors/giacomo/professor.yml

add ln adresse giacomo

---

courses/rgb/en.md

fix / error rgb

---

courses/rgb/course.yml

modify level

---

courses/ln402/course.yml

fix level ln204

---

courses/ln402/course.yml
courses/ln402/de.md
courses/ln402/en.md
courses/ln402/es.md
courses/ln402/fr.md
courses/ln402/it.md
courses/ln402/pt.md

fix ln204 goals

---

courses/rgb/course.yml
courses/rgb/de.md
courses/rgb/en.md
courses/rgb/es.md
courses/rgb/fr.md
courses/rgb/it.md
courses/rgb/pt.md

fix rgb courses imae and time

---

courses/econ204/en.md

fix econ204 name

---

courses/secu101/en.md

fix secu name

---

courses/crypto302/en.md

change crypto 302 name

---

courses/crypto301/en.md

fix en name crypto 301

---

tutorials/privacy/payjoin-samourai-wallet/de.md
tutorials/privacy/payjoin-samourai-wallet/en.md
tutorials/privacy/payjoin-samourai-wallet/es.md
tutorials/privacy/payjoin-samourai-wallet/fr.md
tutorials/privacy/payjoin-samourai-wallet/it.md
tutorials/privacy/payjoin-samourai-wallet/pt.md
tutorials/privacy/payjoin-sparrow-wallet/de.md
tutorials/privacy/payjoin-sparrow-wallet/en.md
tutorials/privacy/payjoin-sparrow-wallet/es.md
tutorials/privacy/payjoin-sparrow-wallet/fr.md
tutorials/privacy/payjoin-sparrow-wallet/it.md
tutorials/privacy/payjoin-sparrow-wallet/pt.md
tutorials/privacy/payjoin/de.md
tutorials/privacy/payjoin/en.md
tutorials/privacy/payjoin/es.md
tutorials/privacy/payjoin/fr.md
tutorials/privacy/payjoin/it.md
tutorials/privacy/payjoin/pt.md
tutorials/privacy/stonewall-x2/de.md
tutorials/privacy/stonewall-x2/en.md
tutorials/privacy/stonewall-x2/es.md
tutorials/privacy/stonewall-x2/fr.md
tutorials/privacy/stonewall-x2/it.md
tutorials/privacy/stonewall-x2/pt.md
tutorials/privacy/stonewall/de.md
tutorials/privacy/stonewall/en.md
tutorials/privacy/stonewall/es.md
tutorials/privacy/stonewall/fr.md
tutorials/privacy/stonewall/it.md
tutorials/privacy/stonewall/pt.md

Cette PR ajoute des liens hypertextes internes entre mes articles récents (payjoins, stonewall et stonewall x2) afin de permettre aux utilisateurs de découvrir des contenus connexes.

Add internal links across my tutorials

---

courses/rgb/de.md
courses/rgb/en.md
courses/rgb/es.md
courses/rgb/fr.md
courses/rgb/it.md
courses/rgb/pt.md

fix error rgb course

---

resources/conference/lecture-saifedean-ammous/events.yml
resources/conference/lnbits-with-ov1/events.yml
resources/conference/using-bitcoin-everyday/events.yml
resources/conference/viaregio_LN_Summit_2024/events.yml

remove website: and add live link

---

courses/btc101/pl.md
courses/btc102/pl.md
courses/crypto301/pl.md
courses/econ201/pl.md
courses/econ204/pl.md
courses/ln201/pl.md
courses/min201/pl.md
courses/secu101/pl.md

This is the initial upload of course in Polish thanks to the automated translation. Translation review would be needed.

initial course upload

---

scripts/convert-to-webp-py/README.md

Je vous avais partagé un script python pour convertir des images en webp et jpeg, mais là, je viens de finir un petit logiciel avec une GUI bien plus complet et facile à utiliser. J'ai donc mis à jour le readme du script pour renvoyer vers mon repo. Si vous souhaitez simplement supprimer ce script, vous pouvez le faire aussi, ça ne m'embête pas.
https://github.com/LoicPandul/ImagesConverter

Update README of a script

---

resources/books/the-bitcoin-standard/book.yml

fix missing m

---

tutorials/privacy/payjoin-samourai-wallet/de.md
tutorials/privacy/payjoin-samourai-wallet/en.md
tutorials/privacy/payjoin-samourai-wallet/es.md
tutorials/privacy/payjoin-samourai-wallet/fr.md
tutorials/privacy/payjoin-samourai-wallet/it.md
tutorials/privacy/payjoin-samourai-wallet/pt.md
tutorials/privacy/payjoin-sparrow-wallet/de.md
tutorials/privacy/payjoin-sparrow-wallet/en.md
tutorials/privacy/payjoin-sparrow-wallet/es.md
tutorials/privacy/payjoin-sparrow-wallet/fr.md
tutorials/privacy/payjoin-sparrow-wallet/it.md
tutorials/privacy/payjoin-sparrow-wallet/pt.md
tutorials/privacy/payjoin/de.md
tutorials/privacy/payjoin/en.md
tutorials/privacy/payjoin/es.md
tutorials/privacy/payjoin/fr.md
tutorials/privacy/payjoin/it.md
tutorials/privacy/payjoin/pt.md

- disclaimer message for the situation ;
- The 6 translations have already been done in the PR. No need for additional translations ;
- links to 404 have been removed ;
- adaptation of the tutorials to explain manual operation without Soroban.

Payjoin tutorials adaptation

---

tutorials/privacy/joinBot/de.md
tutorials/privacy/joinBot/en.md
tutorials/privacy/joinBot/es.md
tutorials/privacy/joinBot/fr.md
tutorials/privacy/joinBot/it.md
tutorials/privacy/joinBot/pt.md

- disclaimer message for the situation ;
- I've redone some translations that weren't quite right ;
- The 6 translations have already been done in the PR. No need for additional translations.

Joinbot tutorial adaptation

---

tutorials/privacy/boltzmann-entropy/de.md
tutorials/privacy/boltzmann-entropy/en.md
tutorials/privacy/boltzmann-entropy/es.md
tutorials/privacy/boltzmann-entropy/fr.md
tutorials/privacy/boltzmann-entropy/it.md
tutorials/privacy/boltzmann-entropy/pt.md

- supression of links pointing to seized sites and 404 ;
- adaptation of tuto ; 
- disclaimer message for the situation.

Boltzman tutorial adaptation

---

courses/btc101/vi.md

Vietnamses review for BTC101

---

resources/bet/infrographiy_anil/fr.yml

fix typo fr

---

courses/crypto301/vi.md
courses/econ204/fr.md
courses/econ204/vi.md

solve bug that were mentionned in #469.

Econ204 fix

---

courses/ln201/en.md
courses/ln201/es.md

Add video translation ln201

---

courses/econ102/fr.md

Corrections terminées, prêt pour la mise à jour.

Relecture bastiat

---

courses/cyp201/cs.md
courses/cyp201/de.md
courses/cyp201/en.md
courses/cyp201/es.md
courses/cyp201/fi.md
courses/cyp201/fr.md
courses/cyp201/it.md
courses/cyp201/pt.md

Proposal to change the name in many languages. 
It used ot be, " Introduction to cryptography" while it was bitcoin use of it. 
I didn't change JP and Vi since it's already bitcoin so i wasn't sure.

Proposal to change CYP course name

---

courses/phi201/fr.md

ok to merge if all good. 
probably ready to be translated after

fix error philo
